"""spotify AT na tabela de refresh_token

Revision ID: 5da5e0c63ec0
Revises: 8d07b5df7efd
Create Date: 2026-09-30 15:31:01.614891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da5e0c63ec0'
down_revision: Union[str, Sequence[str], None] = '8d07b5df7efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('spotify_access_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_token', 'spotify_access_token')
    # ### end Alembic commands ###
